### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by tjunno** [Forbaya/dungeon-generator#1]
Projekti ladattu 29.11.2017 klo 19:30
Aluksi ohjelmaa kääntäessä, jokin vaikutti jäävän ikuiseen looppiin. Tarkemmin katseltuna havaittu että syyllinen lienee DungeonTest-testiluokka jos tuli oikein tulkittua, mutta noin ajettaessa vaikutti sinällään toimivan ja ruudulle piirtyvän jokin muodostelma.
Luokkiin tutustuttaessa kaikki vaikutti päällisin puolin loogisilta. Kun tarkemmin luokkiin perehtyi niin ehkä pinnalle nousi joitain kysymyksiä, vaikkakin voi hyvin olla että vielä tässä vaiheessa kaikki luultavasti on kohtalaisen keskeneräistä. Axis-enum -luokan olemassa olo hieman yllätti pienellä tarjonnallaan/koollaan. Epäilemättä tilanne voi muuttua. Vähäpätöisenä huomiona kooditiedostonpituuden optimoinnissä voisi tietysti käyttää importeissa .* import javafx.scene.*;import javafx.scene.paint.*;import javafx.scene.shape.*; tyyppisiä ratkaisuja javan itse huolehtiessa turhien poisjättämisestä. Ehkä se on makuasia myöskin. JavaFX:stä ei sen suurempaa kokemusta ole.
Testiluokat vaikuttivat toimivan edellämainittua lukuunottamatta ja lienivät riittävät tässä vaiheessa työtä eikä niistä selkeästi mitään huomautettavaa siksi löytynyt. Varmasti nekin kurssin edetessä vielä laajenevat.
Noin vinkkinä voi suositella Gradle, Travis ja Codecov yhdistelmää Mavenin sijasta.
Menestystä loppukurssille!

**Comment by Forbaya** [comment]
Kiitos palautteesta. Axis-enum tulee varmaan katoamaan. Työelämästä olen oppinut olemaan käyttämättä wildcard-importteja (.*). Mielummin enemmän koodirivejä kuin turhia importteja. Täytyy tutkia Gradle + Travis + Codecov comboa.
